id: PDD604463
initial_creation_type: input
source_metadata:
  title: Alak Zenkar Rinpoche
  language: fr
  description: 'Texts by and about the great scholar Alak Zenkar Rinpoche Thupten
    Nyima (a lags gzan dkar thub bstan nyi ma, b.1943):'
  volume:
    367b16035f794fd2b9ce2b8d9bea84ce:
      title: Biography of Jamgön Kongtrul Lodrö Thaye
      parent: Biography
    0130e339a86c44a19a0dd852d34546fb:
      title: Biography of Jamyang Khyentse Wangpo
      parent: Biography
    0f77f7ccff26486984bcd4463edd04f2:
      title: Biography of Patrul Rinpoche
      parent: Biography
    67aad4358a324823bd54ec427dafc155:
      title: Biography of Shechen Gyaltsab Gyurme Pema Namgyal
      parent: Biography
    5d1b2e2490bb4587bf234722805e859e:
      title: Brief Biography of Drakkar Lobzang Palden
      parent: Biography
    d8b0a564efbb4f239fd495285f46f36d:
      title: Brief Biography of Kharlek Tulku Pema Kunzang Rangdrol
      parent: Biography
    d9cf455c37124dacad2b73cbc845f8f3:
      title: Brief Biography of Tāranātha
      parent: Biography
    c1c44baac89345afa9374d53fa8a226b:
      title: A Brief Presentation of the Nine Vehicles
      parent: Buddhist Philosophy
    af239e62c0b54c9b860c7018a6e38aac:
      title: Long Life Prayer for Alak Zenkar Rinpoche
      parent: Long Life Prayers
    90bdfa98c88f4abf89f79ec519c505bc:
      title: Long Life Prayer for Patrick Gaffney (Yeshé Wangyal)
      parent: Long Life Prayers
    c986975a875740fd910226e691be8ce2:
      title: Prayer for the Long Life of Alak Zenkar Rinpoche, the Incarnation of
        Do Khyentsé Yeshé Dorjé
      parent: Long Life Prayers
    b25ac6eeb07f4926ae37b75dda3e5a58:
      title: 'Bodhicaryāvatāra: Teachings and Overview'
      parent: Oral Teachings
    4f2f013458d4430d911432f9b912fb8d:
      title: Light from the Wisdom Sun
      parent: Prayers and Practices
    fc067de1db56436fbe6ac684187c5084:
      title: A Prayer for the Swift Rebirth of Tenpai Nyima Rinpoche
      parent: Swift Rebirth Prayers
    c63509d4110e48cbaf1924d6a51be840:
      title: Prayer for Swift Rebirth of the Fourth Dodrupchen Rinpoche
      parent: Swift Rebirth Prayers
created_at: '2022-02-28T22:37:59.745604'
last_modified_at: '2022-02-28T22:37:59.745607'
